sudo: false
language: haxe

os:
  - linux

haxe:
  - "3.2.1"
  - development

before_install:
    - git clone https://github.com/haxeui/haxeui-core.git --depth=1
    - haxelib dev haxeui-core haxeui-core

install:
    - haxelib install hscript
    - haxelib git luxe https://github.com/underscorediscovery/luxe
    - haxelib git snow https://github.com/underscorediscovery/snow
    - haxelib git flow https://github.com/underscorediscovery/flow
    - haxelib dev haxeui-luxe $TRAVIS_BUILD_DIR


script:
    - haxelib run flow build web --release
